### ISSUE TITLE
Infinite loop when applying impulse to shape

### ISSUE THREAD

**Issue by diarmidmackenzie** [c-frame/aframe-physics-system#24]
Splitting this out as a separate issue as it's not straightforward

Further issue spotted in Cannon example. When clicking to apply an impulse in the compound example. Seems to be specific to this example...

aframe-physics-system.js:18053 Uncaught RangeError: Maximum call stack size exceeded
at LocalDriver.applyBodyMethod (aframe-physics-system.js:18053:3)
at body.applyImpulse [as __applyImpulse] (aframe-physics-system.js:18916:16)
at LocalDriver.applyBodyMethod (aframe-physics-system.js:18053:27)
at body.applyImpulse [as __applyImpulse] (aframe-physics-system.js:18916:16)
at LocalDriver.applyBodyMethod (aframe-physics-system.js:18053:27)
at body.applyImpulse [as __applyImpulse] (aframe-physics-system.js:18916:16)
at LocalDriver.applyBodyMethod (aframe-physics-system.js:18053:27)
at body.applyImpulse [as __applyImpulse] (aframe-physics-system.js:18916:16)
at LocalDriver.applyBodyMethod (aframe-physics-system.js:18053:27)
at body.applyImpulse [as __applyImpulse] (aframe-physics-system.js:18916:16)

**Comment by diarmidmackenzie** [comment]
What I've discovered so far...

When a body has a separate shape component (as per compount shapes), after the shape is initialized, the shape calls `addShape()` on the body, and the body sets the `shouldUpdateBody` flag on itself.

Then on the next tick, the `_play()` function gets called, which calls `this.system.addBody(this.body);`, which results in this code being called for a 2nd time (it was originally called when the body component was initialized)

```
if (this.data.driver === 'local') {
      body.__applyImpulse = body.applyImpulse;
```

The problem is that this code is thus being executed twice, and when this happens, `__applyImpulse` ends up pointing to itself, resulting in an infinite loop.

This doesn't happen when there is no separate `shape` component, as we don't get this double initialization.

What I haven't yet understood is why this problem did not occur in A-Frame 1.3.0.

**Comment by diarmidmackenzie** [comment]
The difference seems to be that when the `body` component is initialized, in [`initBody()` ](https://github.com/c-frame/aframe-physics-system/blob/c864138d2803a6050f0b38ce347c022bea5cef8a/src/components/body/body.js#L94) with 1.4.0, `this.isPlaying` is set, whereas in 1.3.0 it isn't.  That results in `_play()` being called on initialization, and then again as a result of the shouldUpdateBody flag being set.

`isPlaying` flag is managed by A-Frame, so it makes sense that an A-Frame change could change when this gets set.  Not yet sure what changed, though...

**Comment by diarmidmackenzie** [comment]
Done a bit of digging in A-Frame but can't easily identify what has led to this change in ordering.

Ether way, aframe-physics-system should be more robust to this sequence.

Here's an example using A-Frame 1.3.0 that shows the same problem:
https://glitch.com/edit/#!/infinite-loop-apply-impulse?path=index.html%3A30%3A0

So I'm not too bothered what the exact cause of the subtle change in ordering is - we should make aframe-physics-system robust to either order...

**Comment by diarmidmackenzie** [comment]
OK, problem with the fix is fairly simple.

Just as the `play()` processing doesn't allow for the fact that `play()` might have already been called, so the `pause()` processing doesn't allow for the fact that `play()` might not have been called yet.

[This bit of code](https://github.com/c-frame/aframe-physics-system/blob/daf2633dabb20689dabc70977f8b48112540bde2/src/system.js#L397) is problematic when that's the case, as it clears out `body.applyImpulse.` completely. if `body.__applyImpulse` has not been set up.

**Comment by diarmidmackenzie** [comment]
Stepping back, let's look at the overall flow here...

`isLoaded` is set on a body:
- when it's initialized *if* if already has a shape.
- or after `shouldUpdateBody` is set (in the next `tick`)

When `play` is called on the body, play processing is only done if `isLoaded` is set.

So what's curious (and probably the cause of the regression) is why `play` processing is being invoked 1st time around in 1.4.0, prior to the shape being added...

But also, we can make A-Frame physics system resilient by replacing[ this code](https://github.com/c-frame/aframe-physics-system/blob/daf2633dabb20689dabc70977f8b48112540bde2/src/components/body/body.js#L129):

```
      this.isLoaded = true;

      this._play();
```
with this:

```
      this.pause();
      this.isLoaded = true;
      this.play();
```

I've tested that fix with the example at 1.3.0 and 1.4.0, and with [the glitch](https://glitch.com/edit/#!/infinite-loop-on-impulse-fix?path=index.html%3A9%3A17) at 1.3.0 and 1.4.0, and it seems good.

**Comment by diarmidmackenzie** [comment]
> So what's curious (and probably the cause of the regression) is why play processing is being invoked 1st time around in 1.4.0, prior to the shape being added...

OK, this is happening due to[ these lines](https://github.com/c-frame/aframe-physics-system/blob/daf2633dabb20689dabc70977f8b48112540bde2/src/components/body/body.js#L94-L96):

```
    // If component wasn't initialized when play() was called, finish up.
    if (this.isPlaying) {
      this._play();
    }
```

The `isPlaying` flag is managed by A-Frame, and it's clearly possible for this to be set when the `isLoading` flag is not set.  But if we go ahead and call `_play()` when isLoading is not set, that's likely t cause problems.

Therefore an alternative fix is probably just to modify the code above to this:

```
    // If component wasn't initialized when play() was called, finish up.
    if (this.isPlaying) {
      this.play();
    }
```

(then `_play()` will only be invoked if `isLoaded` is set).

**Comment by diarmidmackenzie** [comment]
Turns out that fix doesn't work, because `this.play()` is not invoked directly, but via the the A-Frame `wrapPlay()` method, which then doesn't invoke the components `play()` because that wrapper has [code](https://github.com/aframevr/aframe/blob/f5f2790eca841bf633bdaa0110b0b59d36d7e854/src/core/component.js#L788) that de-duplicates calls to `play()`

But this fix does work:
```
if (this.isPlaying) {
      if (this.isLoaded) this._play();
    }
```

Or rather, this fixes the original problem described in this issue.  But it doesn't fix the glitch, because the glitch had engineered a different route to duplicate calls to `play()`, which is not addressed by this alternative fix.
