### ISSUE TITLE
New error hit in Cannon Worker Driver ttl example (A-Frame 1.4.0)

### ISSUE THREAD

**Issue by diarmidmackenzie** [c-frame/aframe-physics-system#25]
Breaking out as a separate issue as it doesn't sem simple, and I'm not sure I want to investigate futher.

ttl: Hits new error. This example also works better than it did in 1.3.0 - shapes don't fall through floor. Also hits pre-existing (i.e. also with 1.3.0) "Unimplemented shape" error

11:57:20.209 aframe-physics-system.js:19146 Uncaught TypeError: Cannot read properties of undefined (reading 'position')
at module.exports.deserializeInterpBodyUpdate (aframe-physics-system.js:19146:8)
at WorkerDriver.step (aframe-physics-system.js:18262:16)
at i.tick (aframe-physics-system.js:18813:17)
at v.tick (a-scene.js:703:36)
at v.render (a-scene.js:743:32)
at bind.js:12:17
at three.module.js:28350:35
at r (three.module.js:12556:3)

Error is hit in this code:

```
  for (var id in prevFrame.bodies) {
    if (prevFrame.bodies.hasOwnProperty(id) && nextFrame.bodies.hasOwnProperty(id)) {
      protocol.deserializeInterpBodyUpdate(
        prevFrame.bodies[id],
        nextFrame.bodies[id],
        this.bodies[id],
        mix
      );
    }
  }
```

Problem is that `this.bodies["body_1"]` is undefined.  Presumably this is the body that's just been removed from the scene.  So it seems that some data is coming back from the physics system (worker driver) and it's failing to correlate with a body that's been removed from the scene.

I suspect this is a race condition when removing the body from the scene.  It only seems to happen once, even though the above code is in tick() processing.

No idea why this didn't happen in A-Frame 1.3.0 and now happens with A-Frame 1.4.0.

It's probably simple enough to fix y thandlng the case where the body is undefined, and just ignoring the update.  Could make a fix along those lines, but only worth doing if the Cannon Worker driver is going to be maintained long term.

As things stand it has so many issues, that I think it's probably better to retire it, in which case no point spending time fixing this...

**Comment by diarmidmackenzie** [comment]
Nobody seems to care about Cannon Workers, so closing.
